Adding Basic Auth in http transport channel with X-SAP-Hive-PasswdAut…
Altiscale/hive pull request #22
Opened 2018-09-05 05:15 UTC by narendra-altiscale

1. Basic auth is supported with http channel for hive jwt token with additional header "X-SAP-Hive-PasswdAuth" set to true
2. New class added to support this password authentication provider
3. I tested this successfully in cluster(naren4635) with this
beeline -u "jdbc:hive2://hiveserver-naren4635.test.altiscale.com:10001/default;transportMode=http;httpPath=cliservice;http.header.X-SAP-Hive-PasswdAuth=true;http.header.Authorization=Basic <username>:<jwtoken>"
Note that you don't need to do basic 64 encoding in the above as the beeline automatically does this for you.
Thanks,
Narendra

2018-09-05 22:17 UTC, johannes-altiscale requested changes
neat! but, pls check on the header and header value

2018-09-05 22:17 UTC, johannes-altiscale commented on service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
> +  private static final String X_SAP_HIVE_PASSWDAUTH = "X-SAP-Hive-PasswdAuth";
this should be x-http-authtype, see also https://github.com/VertiCloud/alti_apiproxy_app-cookbook/blob/master/templates/default/init.lua.erb#L9-L10

The client will send a `x-http-authtype: Basic` header to indicate to the server that Basic auth is requested

2018-09-05 23:40 UTC, narendra-altiscale commented
1. Code is changed to  the header x-http-authtype:Basic. Please check.
2. SSL works as expected. After setting the three parameters in hive-site.xml, the new beeline command is here

beeline -u "jdbc:hive2://hiveserver-naren4635.test.altiscale.com:10001/default;transportMode=http;httpPath=cliservice;ssl=true;sslTrustStore=/etc/altiscale/secrets/truststore.jks;trustStorePassword=changeit;http.header.x-http-authtype=Basic;http.header.Authorization= Basic username:jwtoken"

2018-09-06 04:00 UTC, bala-altiscale commented on service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
> +        //Check if sap auth header is present and if so use this custom class that we created
minor cosmetic change: replace sap auth header with http auth header

2018-09-06 04:05 UTC, bala-altiscale reviewed
Do you plan to write respective unit tests as part of another PR later? If so, the changes look good to me.

2018-09-08 17:52 UTC, johannes-altiscale approved these changes

2018-10-09 21:27 UTC, cetin-altiscale reviewed
Overall, looks good to me. My comments are mostly because of extra lines. I also seconded Bala's comment. Please address them before progressing further.

2018-10-09 21:27 UTC, cetin-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbWithCustomAuthHttpWithKerberos.java
> +
extra line.

2018-10-09 21:27 UTC, cetin-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbWithCustomAuthHttpWithKerberos.java
> +
extra line.

2018-10-09 21:27 UTC, cetin-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbWithCustomAuthHttpWithKerberos.java
> +
extra line.

2018-10-09 21:27 UTC, cetin-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbWithCustomAuthHttpWithKerberos.java
> +    private static final Logger LOG = LoggerFactory.getLogger(TestSSL.class);
minor thing but would be better to have variables defined before getJDBCURL function above for convenience.

2018-10-09 21:27 UTC, cetin-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbWithCustomAuthHttpWithKerberos.java
> +
extra line.

2018-10-09 21:27 UTC, cetin-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbWithCustomAuthHttpWithKerberos.java
> +
extra line.

2018-10-09 21:27 UTC, cetin-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbWithCustomAuthHttpWithKerberos.java
> +
extra line.

2018-10-09 21:27 UTC, cetin-altiscale commented on service/src/java/org/apache/hive/service/auth/CustomAuthWithKerberosImpl.java
> +
extra line.

2018-10-09 21:27 UTC, cetin-altiscale commented on service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
> +        //Check if sap auth header is present and if so use this custom class that we created
+1.

2018-10-09 23:55 UTC, narendra-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbWithCustomAuthHttpWithKerberos.java
> +
Hi @cetin-altiscale , I have removed the extra newlines and formatted the code and corrected the comment for SAP. Please check now.
Thanks,
Narendra

2018-10-10 00:15 UTC, cetin-altiscale approved these changes
It looks like I missed two minor space issues. It would be great if you fix them before merging. Other than these, looks good.

2018-10-10 00:15 UTC, cetin-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/MiniHiveKdc.java
> +       miniHiveKdc.getFullyQualifiedServicePrincipal(MiniHiveKdc.HIVE_SERVICE_PRINCIPAL,null);
please add a space between comma and null.

2018-10-10 00:15 UTC, cetin-altiscale commented on itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/MiniHiveKdc.java
> +       miniHiveKdc.getServicePrincipalForUser(MiniHiveKdc.HIVE_SERVICE_PRINCIPAL,null));
same here.

2018-10-10 16:44 UTC, merged